map, all tests are ok
rewiel/ru-study-python pull request #2
Opened 2022-10-26 09:50 UTC by rewiel

2022-10-26 10:18 UTC, aleksandr-semenov-dbp requested changes

2022-10-26 10:18 UTC, aleksandr-semenov-dbp commented on exercises/map.py
> +                    )
здесь просто тьма лишних действий если цель стоит посчитать запятые в строчке

2022-10-26 10:18 UTC, aleksandr-semenov-dbp commented on exercises/map.py
> +        list_of_rating = list(filter(lambda x: x, list(map(_filter_rating, list_of_movies))))
что-то как-то запутано все... _filter_rating() несмотря на название ничего не фильтрует и не используется для фильтрации, как будто мы что-то не по назначению используем. В условии задачи действительно есть условия фильтрации, и filter - весьма подходящая функция, и надо делать как она задумана, там где условие - давать функцию вычисляющую условие, а не странноватую `lambda x:x`

2022-10-26 10:18 UTC, aleksandr-semenov-dbp commented on exercises/map.py
> +                    f"""{e} - в строчке с назвнаием фильма {movie.get("name")},
опечатка в "названием"

2022-10-26 10:18 UTC, aleksandr-semenov-dbp commented on exercises/map.py
> +        return sum(list(map(_filter_rating, list_of_movies)))
list() здесь уже не нужен, название функции _filter_rating() как мне кажется не соответствует тому что она делает.

2022-10-26 11:16 UTC, rewiel commented on exercises/map.py
> +                    )
Цель была проверить, что в поле страны у нас +- адекватные названия стран, а не "          ,          " что-то такое.  Первый вариант был семантически нагруженным, переписал на более приятный

2022-10-26 11:24 UTC, rewiel commented on exercises/map.py
> +                    f"""{e} - в строчке с назвнаием фильма {movie.get("name")},
исправил, спасибо

2022-10-26 11:28 UTC, rewiel commented on exercises/map.py
> +        list_of_rating = list(filter(lambda x: x, list(map(_filter_rating, list_of_movies))))
суть функции - фильтрануть входной словарь по условиям и вернуть значения удовлетворяющие условию.
Мы возвращаем значения, и нам нужно избавиться от None, поэтому и используется конструкция lambda x:x -> переписал в lambda x:x is not None.

2022-10-26 11:29 UTC, rewiel commented on exercises/map.py
> +        return sum(list(map(_filter_rating, list_of_movies)))
list убрал, sum работает с map и без него. Функцию переименовал

2022-10-27 22:23 UTC, aleksandr-semenov-dbp requested changes

2022-10-27 22:23 UTC, aleksandr-semenov-dbp commented on exercises/map.py
> +                    f"""{e} - в строчке с назвнаием фильма {movie.get("name")},
здесь опечатка осталась

2022-10-27 22:23 UTC, aleksandr-semenov-dbp commented on exercises/map.py
> +                    )
Это все может годится для олимпиады, но в реальном промышленном программировании на питоне самое главное - упростить читаемость кода для тех кто будет его дальше исправлять/сопровождать, а на втором месте - эффективность, а 

```
sum(
                         [
                             0 if country.isspace() else 1
                             for country in movie.get("country").split(",")
                         ]
)
```
это не только очень неэффективной (split() создает новые объекты, [] здесь вообще не нужны), но и запутанный способ вызвать `count(",")`. 

Надо переделать. Надо сделать функцию проверки условия из задачи, взять map-ом рейтинги отфильтрованного и просуммировать их, тогда это будет легко читать и поддерживать.

2022-10-29 17:02 UTC, aleksandr-semenov-dbp approved these changes

2022-10-31 08:18 UTC, merged